#!/bin/bash

echo "🚀 Personal OS - Vercel Deployment"
echo "===================================="
echo ""

echo "Please deploy to Vercel:"
echo ""
echo "1. Go to: https://vercel.com/new"
echo "2. Click 'Import Git Repository'"
echo "3. Select your 'personal-os' repository"
echo "4. Click 'Import'"
echo ""
echo "5. Add these Environment Variables:"
echo "   - NEXT_PUBLIC_SUPABASE_URL = https://njswmuhfcfqgeydzuose.supabase.co"
echo "   - NEXT_PUBLIC_SUPABASE_ANON_KEY = (copy from .env.local)"
echo "   - SUPABASE_SERVICE_ROLE_KEY = (copy from .env.local)"
echo ""
echo "6. Click 'Deploy'"
echo ""
echo "Wait for deployment to complete (2-3 minutes)..."
echo ""
read -p "Press Enter when deployment is complete..."

echo ""
read -p "Enter your Vercel deployment URL (e.g., https://personal-os.vercel.app): " VERCEL_URL

echo ""
echo "✅ Deployment complete!"
echo ""
echo "🔗 Your app: $VERCEL_URL"
echo ""
echo "⚠️  IMPORTANT: Update Supabase Auth URLs"
echo ""
echo "Go to: https://supabase.com/dashboard/project/njswmuhfcfqgeydzuose/auth/url-configuration"
echo ""
echo "Add these URLs to 'Redirect URLs':"
echo "  - $VERCEL_URL/**"
echo "  - $VERCEL_URL/auth/callback"
echo ""
echo "Then test your app!"
